#
###################################
# Site wide configuration
####################################
#
title: Imaginative Culprits
email: editorial.iitmandi@gmail.com
description: A weblog that exists to sustain the literary culture of the campus. We bring to you stories from IIT Mandi and beyond.
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: http://www.imaginativeculprits.com

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Imaginative Culprits
  avatar:
  job: Literary Society, IIT Mandi
  bio: "A weblog that exists to cater to literary needs of the IIT Mandi student community and to keep the writers/readers/bibliophiles in us from suffering from existential crises. We bring to you stories from IIT Mandi and beyond."
  email: editorial.iitmandi@gmail.com
  disqus-shortname: imaginativeculprits
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-78225619-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
